# Generated by Django 5.2.3 on 2025-06-16 06:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('text', models.CharField(max_length=5000)),
                ('category', models.CharField(max_length=32)),
                ('location_x', models.FloatField()),
                ('location_y', models.FloatField()),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('done', models.BooleanField(default=False)),
                ('condition', models.CharField(max_length=16)),
            ],
        ),
    ]
