# Generated by Django 5.2.3 on 2025-06-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='address',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
