# Generated by Django 5.2.3 on 2025-06-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_record_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='location_x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='record',
            name='location_y',
            field=models.FloatField(default=0),
        ),
    ]
