# Generated by Django 5.2.3 on 2025-06-17 12:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_record_location_x_alter_record_location_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
