# Generated by Django 5.2.3 on 2025-06-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='calendar_id',
            field=models.IntegerField(default=0),
        ),
    ]
