# Generated by Django 5.2.3 on 2025-06-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_record_calendar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='calendar_id',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
